"""Add a slug field for outbox objects

Revision ID: b28c0551c236
Revises: 604d125ea2fb
Create Date: 2022-10-30 14:09:14.540461+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b28c0551c236'
down_revision = '604d125ea2fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_outbox_slug'), ['slug'], unique=False)

    # ### end Alembic commands ###

    # Backfill the slug for existing articles. A table stub with just the
    # columns this revision knows about, not the live `OutboxObject` model:
    # the model also maps every column later migrations add, so selecting
    # through it fails on any DB that isn't already at head.
    from app.utils.text import slugify
    outbox = sa.table(
        "outbox",
        sa.column("id", sa.Integer),
        sa.column("ap_type", sa.String),
        sa.column("ap_object", sa.JSON),
        sa.column("slug", sa.String),
    )
    bind = op.get_bind()
    articles = bind.execute(
        sa.select(outbox.c.id, outbox.c.ap_object).where(
            outbox.c.ap_type == "Article"
        )
    ).all()
    for article_id, ap_object in articles:
        bind.execute(
            outbox.update()
            .where(outbox.c.id == article_id)
            .values(slug=slugify(ap_object["name"]))
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
