"""add actor outbox_backfilled_at

Revision ID: bd38c89e83de
Revises: 6aafc8f7dd54
Create Date: 2026-07-15 10:22:15.250645+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'bd38c89e83de'
down_revision = '6aafc8f7dd54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outbox_backfilled_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.drop_column('outbox_backfilled_at')

    # ### end Alembic commands ###
