"""add marker table

Revision ID: 420fe79fe4da
Revises: 4c9a1f7b2e58
Create Date: 2026-08-01 10:30:00.000000+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '420fe79fe4da'
down_revision = '4c9a1f7b2e58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'marker',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('timeline', sa.String(), nullable=False),
        sa.Column('last_read_id', sa.String(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_marker_id'), 'marker', ['id'], unique=False)
    op.create_index(op.f('ix_marker_timeline'), 'marker', ['timeline'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marker_timeline'), table_name='marker')
    op.drop_index(op.f('ix_marker_id'), table_name='marker')
    op.drop_table('marker')
    # ### end Alembic commands ###
