"""add actor mute columns

Revision ID: 4c9a1f7b2e58
Revises: 33d3ae2dedac
Create Date: 2026-08-01 01:00:00.000000+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '4c9a1f7b2e58'
down_revision = '33d3ae2dedac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_muted', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('muted_until', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('are_notifications_muted', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.drop_column('are_notifications_muted')
        batch_op.drop_column('muted_until')
        batch_op.drop_column('is_muted')

    # ### end Alembic commands ###
