"""add muted_conversation table

Revision ID: b3e7a1f0c9d4
Revises: 9f1c3d7a5b21
Create Date: 2026-08-08 23:50:00.000000+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'b3e7a1f0c9d4'
down_revision = '9f1c3d7a5b21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'muted_conversation',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversation', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('conversation'),
    )
    with op.batch_alter_table('muted_conversation', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_muted_conversation_conversation'), ['conversation'], unique=True
        )
        batch_op.create_index(
            batch_op.f('ix_muted_conversation_id'), ['id'], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('muted_conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_muted_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_muted_conversation_conversation'))

    op.drop_table('muted_conversation')

    # ### end Alembic commands ###
