"""add actor counts cache

Revision ID: 33d3ae2dedac
Revises: bd38c89e83de
Create Date: 2026-07-15 17:06:29.717115+00:00

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '33d3ae2dedac'
down_revision = 'bd38c89e83de'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followers_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('following_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('statuses_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('counts_refreshed_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('actor', schema=None) as batch_op:
        batch_op.drop_column('counts_refreshed_at')
        batch_op.drop_column('statuses_count')
        batch_op.drop_column('following_count')
        batch_op.drop_column('followers_count')

    # ### end Alembic commands ###
